services:
  servidor_preguntas:
    build: .
    ports:
      - "0.0.0.0:8888:8888/tcp"  # Escucha IPv4 e IPv6 con dual-stack
    volumes:
      - ./logs:/app/logs
    networks:
      red_ipv6:

networks:
  red_ipv6:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: "fd00:dead:beef::/64"